### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by blink1073** [edgeflip/dispatch#2]
Hi!  We also have a project named `paperboy`, and were hoping to release on PyPI.  Given that this repo has been inactive for 5 years, would you be willing to transferring ownership?

cf https://github.com/timkpaine/paperboy/issues/67

**Comment by jesteria** [comment]
Hey, that's too bad that there's a name conflict. You're right, I haven't had to work on this port for a while, and it hasn't been massively adopted or anything :smile: 

That said, it is operable, and referenced by a couple other projects (requirements.txt / setup.py). I don't think changing what it is in PyPI (by transferring ownership of the name) would be expedient.

All the good names are taken, I know. (I was literally just thinking of naming something `abba` – but, taken.)

Good luck!

**Comment by blink1073** [comment]
Cheers, thanks for the quick response!

**Comment by timkpaine** [comment]
Github says its used by 2 other projects:
https://github.com/gbozee/django-paystack/blob/master/setup.py#L24
https://github.com/edgeflip/faraday

I'm happy to do the PR into django-paystack. Given that the import name is `dispatch` anyway, it will be a bit confusing if `paperboy` is imported as `dispatch` but `paperboy-jupyter` is imported as `paperboy`.

**Comment by timkpaine** [comment]
looks like `django-dispatch` is available, but might be confusing if this is meant to be separate from django

**Comment by blink1073** [comment]
I think @timkpaine's approach above is reasonable.  Otherwise, we'd be well within bounds to attempt https://www.python.org/dev/peps/pep-0541/.
